// flow-typed signature: 38981ae21418cc2626b345e743ea16a9
// flow-typed version: <<STUB>>/lokijs_v^1.5.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lokijs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lokijs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lokijs/build/loki-indexed-adapter.min' {
  declare module.exports: any;
}

declare module 'lokijs/build/lokijs.min' {
  declare module.exports: any;
}

declare module 'lokijs/karma.build.conf' {
  declare module.exports: any;
}

declare module 'lokijs/karma.conf' {
  declare module.exports: any;
}

declare module 'lokijs/src/jquery-sync-adapter' {
  declare module.exports: any;
}

declare module 'lokijs/src/loki-angular' {
  declare module.exports: any;
}

declare module 'lokijs/src/loki-crypted-file-adapter' {
  declare module.exports: any;
}

declare module 'lokijs/src/loki-fs-structured-adapter' {
  declare module.exports: any;
}

declare module 'lokijs/src/loki-incremental-adapter' {
  declare module.exports: any;
}

declare module 'lokijs/src/loki-indexed-adapter' {
  declare module.exports: any;
}

declare module 'lokijs/src/loki-nativescript-adapter' {
  declare module.exports: any;
}

declare module 'lokijs/src/lokijs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lokijs/build/loki-indexed-adapter.min.js' {
  declare module.exports: $Exports<'lokijs/build/loki-indexed-adapter.min'>;
}
declare module 'lokijs/build/lokijs.min.js' {
  declare module.exports: $Exports<'lokijs/build/lokijs.min'>;
}
declare module 'lokijs/karma.build.conf.js' {
  declare module.exports: $Exports<'lokijs/karma.build.conf'>;
}
declare module 'lokijs/karma.conf.js' {
  declare module.exports: $Exports<'lokijs/karma.conf'>;
}
declare module 'lokijs/src/jquery-sync-adapter.js' {
  declare module.exports: $Exports<'lokijs/src/jquery-sync-adapter'>;
}
declare module 'lokijs/src/loki-angular.js' {
  declare module.exports: $Exports<'lokijs/src/loki-angular'>;
}
declare module 'lokijs/src/loki-crypted-file-adapter.js' {
  declare module.exports: $Exports<'lokijs/src/loki-crypted-file-adapter'>;
}
declare module 'lokijs/src/loki-fs-structured-adapter.js' {
  declare module.exports: $Exports<'lokijs/src/loki-fs-structured-adapter'>;
}
declare module 'lokijs/src/loki-incremental-adapter.js' {
  declare module.exports: $Exports<'lokijs/src/loki-incremental-adapter'>;
}
declare module 'lokijs/src/loki-indexed-adapter.js' {
  declare module.exports: $Exports<'lokijs/src/loki-indexed-adapter'>;
}
declare module 'lokijs/src/loki-nativescript-adapter.js' {
  declare module.exports: $Exports<'lokijs/src/loki-nativescript-adapter'>;
}
declare module 'lokijs/src/lokijs.js' {
  declare module.exports: $Exports<'lokijs/src/lokijs'>;
}
