// flow-typed signature: 6dc42693b27f14a800ad64278002f0a4
// flow-typed version: <<STUB>>/react-three-renderer_v^3.1.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-three-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-three-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-three-renderer/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/decorators/resource' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/BoxGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/BufferGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/BufferGeometryDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/CircleBufferGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/CircleGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/CylinderGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/DodecahedronGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/EdgesGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/ExtrudeGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/GeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/GeometryDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/GeometryWithShapesDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/IcosahedronGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/LatheGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/OctahedronGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/ParametricGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/PlaneBufferGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/PlaneGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/PolyhedronGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/PolyhedronGeometryDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/RingGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/ShapeGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/AbsArcDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/AbsEllipseDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/BezierCurveToDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/HoleDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/LineToDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/MoveToDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/PathDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/QuadraticCurveToDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/ShapeActionDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/ShapeDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/SplineThruDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/SphereGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/TetrahedronGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/TextGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/TorusGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/TorusKnotGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Geometry/TubeGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Light/AmbientLightDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Light/DirectionalLightDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Light/HemisphereLightDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Light/LightDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Light/PointLightDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Light/SpotLightDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/LineBasicMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/LineDashedMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/MaterialDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/MeshBasicMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/MeshDepthMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/MeshLambertMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/MeshNormalMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/MeshPhongMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/MeshStandardMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/PointsMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/RawShaderMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/ShaderMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/SpriteMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/TextureDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/UniformDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Material/UniformsDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/ModuleDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/Camera/CameraDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/Camera/CubeCameraDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/Camera/OrthographicCameraDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/Camera/PerspectiveCameraDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/GroupDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/Helper/ArrowHelperDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/Helper/AxisHelperDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/Helper/CameraHelperDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/Helper/GridHelperDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/LineDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/LineSegmentsDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/MeshDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/Object3DDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/PointsDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/SceneDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Object/SpriteDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/React3Descriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Resource/GeometryResourceDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Resource/MaterialResourceDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Resource/ResourceDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Resource/ResourcesDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Resource/ShapeGeometryResourceDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Resource/ShapeResourceDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/Resource/TextureResourceDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/THREEElementDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/descriptors/ViewportDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/ElementDescriptorContainer' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/InternalComponent' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Module' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/React3' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/React3ComponentFlags' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/React3ComponentTree' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/React3CompositeComponentWrapper' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/React3ContainerInfo' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/React3Instance' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/React3Renderer' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Resources/ResourceContainer' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Resources/ResourceReference' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Resources/ShapeResourceReference' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Shapes/AbsArcAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Shapes/AbsEllipseAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Shapes/BezierCurveToAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Shapes/HoleAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Shapes/LineToAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Shapes/MoveToAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Shapes/QuadraticCurveToAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Shapes/ShapeAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Shapes/SplineThruAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Uniform' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/UniformContainer' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/utils/CameraUtils' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/utils/EventDispatcher' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/utils/idPropertyName' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/utils/isWebglSupported' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/utils/PropTypeError' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/utils/propTypeInstanceOf' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/utils/removeDevTool' {
  declare module.exports: any;
}

declare module 'react-three-renderer/lib/Viewport' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/index' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/decorators/resource' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/BoxGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/BufferGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/BufferGeometryDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/CircleBufferGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/CircleGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/CylinderGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/DodecahedronGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/EdgesGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/ExtrudeGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/GeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/GeometryDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/GeometryWithShapesDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/IcosahedronGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/LatheGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/OctahedronGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/ParametricGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/PlaneBufferGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/PlaneGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/PolyhedronGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/PolyhedronGeometryDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/RingGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/ShapeGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/AbsArcDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/AbsEllipseDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/BezierCurveToDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/HoleDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/LineToDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/MoveToDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/PathDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/QuadraticCurveToDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/ShapeActionDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/ShapeDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/SplineThruDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/SphereGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/TetrahedronGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/TextGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/TorusGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/TorusKnotGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Geometry/TubeGeometryDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Light/AmbientLightDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Light/DirectionalLightDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Light/HemisphereLightDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Light/LightDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Light/PointLightDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Light/SpotLightDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/LineBasicMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/LineDashedMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/MaterialDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/MeshBasicMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/MeshDepthMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/MeshLambertMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/MeshNormalMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/MeshPhongMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/MeshStandardMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/PointsMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/RawShaderMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/ShaderMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/SpriteMaterialDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/TextureDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/UniformDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Material/UniformsDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/ModuleDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/Camera/CameraDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/Camera/CubeCameraDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/Camera/OrthographicCameraDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/Camera/PerspectiveCameraDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/GroupDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/Helper/ArrowHelperDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/Helper/AxisHelperDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/Helper/CameraHelperDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/Helper/GridHelperDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/LineDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/LineSegmentsDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/MeshDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/Object3DDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/PointsDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/SceneDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Object/SpriteDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/React3Descriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Resource/GeometryResourceDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Resource/MaterialResourceDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Resource/ResourceDescriptorBase' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Resource/ResourcesDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Resource/ShapeGeometryResourceDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Resource/ShapeResourceDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/Resource/TextureResourceDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/THREEElementDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/descriptors/ViewportDescriptor' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/ElementDescriptorContainer' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/InternalComponent' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Module' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/React3' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/React3ComponentFlags' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/React3ComponentTree' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/React3CompositeComponentWrapper' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/React3ContainerInfo' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/React3Instance' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/React3Renderer' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Resources/ResourceContainer' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Resources/ResourceReference' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Resources/ShapeResourceReference' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Shapes/AbsArcAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Shapes/AbsEllipseAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Shapes/BezierCurveToAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Shapes/HoleAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Shapes/LineToAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Shapes/MoveToAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Shapes/QuadraticCurveToAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Shapes/ShapeAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Shapes/SplineThruAction' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Uniform' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/UniformContainer' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/utils/CameraUtils' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/utils/EventDispatcher' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/utils/idPropertyName' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/utils/isWebglSupported' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/utils/PropTypeError' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/utils/propTypeInstanceOf' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/utils/removeDevTool' {
  declare module.exports: any;
}

declare module 'react-three-renderer/src/lib/Viewport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-three-renderer/gulpfile.babel.js' {
  declare module.exports: $Exports<'react-three-renderer/gulpfile.babel'>;
}
declare module 'react-three-renderer/lib/descriptors/decorators/resource.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/decorators/resource'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/BoxGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/BoxGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/BufferGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/BufferGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/BufferGeometryDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/BufferGeometryDescriptorBase'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/CircleBufferGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/CircleBufferGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/CircleGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/CircleGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/CylinderGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/CylinderGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/DodecahedronGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/DodecahedronGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/EdgesGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/EdgesGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/ExtrudeGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/ExtrudeGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/GeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/GeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/GeometryDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/GeometryDescriptorBase'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/GeometryWithShapesDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/GeometryWithShapesDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/IcosahedronGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/IcosahedronGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/LatheGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/LatheGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/OctahedronGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/OctahedronGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/ParametricGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/ParametricGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/PlaneBufferGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/PlaneBufferGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/PlaneGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/PlaneGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/PolyhedronGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/PolyhedronGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/PolyhedronGeometryDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/PolyhedronGeometryDescriptorBase'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/RingGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/RingGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/ShapeGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/ShapeGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/AbsArcDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/Shapes/AbsArcDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/AbsEllipseDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/Shapes/AbsEllipseDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/BezierCurveToDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/Shapes/BezierCurveToDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/HoleDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/Shapes/HoleDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/LineToDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/Shapes/LineToDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/MoveToDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/Shapes/MoveToDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/PathDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/Shapes/PathDescriptorBase'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/QuadraticCurveToDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/Shapes/QuadraticCurveToDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/ShapeActionDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/Shapes/ShapeActionDescriptorBase'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/ShapeDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/Shapes/ShapeDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/Shapes/SplineThruDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/Shapes/SplineThruDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/SphereGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/SphereGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/TetrahedronGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/TetrahedronGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/TextGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/TextGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/TorusGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/TorusGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/TorusKnotGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/TorusKnotGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Geometry/TubeGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Geometry/TubeGeometryDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Light/AmbientLightDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Light/AmbientLightDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Light/DirectionalLightDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Light/DirectionalLightDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Light/HemisphereLightDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Light/HemisphereLightDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Light/LightDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Light/LightDescriptorBase'>;
}
declare module 'react-three-renderer/lib/descriptors/Light/PointLightDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Light/PointLightDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Light/SpotLightDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Light/SpotLightDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/LineBasicMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/LineBasicMaterialDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/LineDashedMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/LineDashedMaterialDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/MaterialDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/MaterialDescriptorBase'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/MeshBasicMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/MeshBasicMaterialDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/MeshDepthMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/MeshDepthMaterialDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/MeshLambertMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/MeshLambertMaterialDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/MeshNormalMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/MeshNormalMaterialDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/MeshPhongMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/MeshPhongMaterialDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/MeshStandardMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/MeshStandardMaterialDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/PointsMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/PointsMaterialDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/RawShaderMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/RawShaderMaterialDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/ShaderMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/ShaderMaterialDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/SpriteMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/SpriteMaterialDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/TextureDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/TextureDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/UniformDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/UniformDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Material/UniformsDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Material/UniformsDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/ModuleDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/ModuleDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/Camera/CameraDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/Camera/CameraDescriptorBase'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/Camera/CubeCameraDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/Camera/CubeCameraDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/Camera/OrthographicCameraDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/Camera/OrthographicCameraDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/Camera/PerspectiveCameraDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/Camera/PerspectiveCameraDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/GroupDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/GroupDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/Helper/ArrowHelperDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/Helper/ArrowHelperDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/Helper/AxisHelperDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/Helper/AxisHelperDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/Helper/CameraHelperDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/Helper/CameraHelperDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/Helper/GridHelperDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/Helper/GridHelperDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/LineDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/LineDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/LineSegmentsDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/LineSegmentsDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/MeshDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/MeshDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/Object3DDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/Object3DDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/PointsDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/PointsDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/SceneDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/SceneDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Object/SpriteDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Object/SpriteDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/React3Descriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/React3Descriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Resource/GeometryResourceDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Resource/GeometryResourceDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Resource/MaterialResourceDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Resource/MaterialResourceDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Resource/ResourceDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Resource/ResourceDescriptorBase'>;
}
declare module 'react-three-renderer/lib/descriptors/Resource/ResourcesDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Resource/ResourcesDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Resource/ShapeGeometryResourceDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Resource/ShapeGeometryResourceDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Resource/ShapeResourceDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Resource/ShapeResourceDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/Resource/TextureResourceDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/Resource/TextureResourceDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/THREEElementDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/THREEElementDescriptor'>;
}
declare module 'react-three-renderer/lib/descriptors/ViewportDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/descriptors/ViewportDescriptor'>;
}
declare module 'react-three-renderer/lib/ElementDescriptorContainer.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/ElementDescriptorContainer'>;
}
declare module 'react-three-renderer/lib/InternalComponent.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/InternalComponent'>;
}
declare module 'react-three-renderer/lib/Module.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Module'>;
}
declare module 'react-three-renderer/lib/React3.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/React3'>;
}
declare module 'react-three-renderer/lib/React3ComponentFlags.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/React3ComponentFlags'>;
}
declare module 'react-three-renderer/lib/React3ComponentTree.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/React3ComponentTree'>;
}
declare module 'react-three-renderer/lib/React3CompositeComponentWrapper.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/React3CompositeComponentWrapper'>;
}
declare module 'react-three-renderer/lib/React3ContainerInfo.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/React3ContainerInfo'>;
}
declare module 'react-three-renderer/lib/React3Instance.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/React3Instance'>;
}
declare module 'react-three-renderer/lib/React3Renderer.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/React3Renderer'>;
}
declare module 'react-three-renderer/lib/Resources/ResourceContainer.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Resources/ResourceContainer'>;
}
declare module 'react-three-renderer/lib/Resources/ResourceReference.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Resources/ResourceReference'>;
}
declare module 'react-three-renderer/lib/Resources/ShapeResourceReference.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Resources/ShapeResourceReference'>;
}
declare module 'react-three-renderer/lib/Shapes/AbsArcAction.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Shapes/AbsArcAction'>;
}
declare module 'react-three-renderer/lib/Shapes/AbsEllipseAction.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Shapes/AbsEllipseAction'>;
}
declare module 'react-three-renderer/lib/Shapes/BezierCurveToAction.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Shapes/BezierCurveToAction'>;
}
declare module 'react-three-renderer/lib/Shapes/HoleAction.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Shapes/HoleAction'>;
}
declare module 'react-three-renderer/lib/Shapes/LineToAction.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Shapes/LineToAction'>;
}
declare module 'react-three-renderer/lib/Shapes/MoveToAction.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Shapes/MoveToAction'>;
}
declare module 'react-three-renderer/lib/Shapes/QuadraticCurveToAction.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Shapes/QuadraticCurveToAction'>;
}
declare module 'react-three-renderer/lib/Shapes/ShapeAction.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Shapes/ShapeAction'>;
}
declare module 'react-three-renderer/lib/Shapes/SplineThruAction.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Shapes/SplineThruAction'>;
}
declare module 'react-three-renderer/lib/Uniform.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Uniform'>;
}
declare module 'react-three-renderer/lib/UniformContainer.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/UniformContainer'>;
}
declare module 'react-three-renderer/lib/utils/CameraUtils.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/utils/CameraUtils'>;
}
declare module 'react-three-renderer/lib/utils/EventDispatcher.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/utils/EventDispatcher'>;
}
declare module 'react-three-renderer/lib/utils/idPropertyName.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/utils/idPropertyName'>;
}
declare module 'react-three-renderer/lib/utils/isWebglSupported.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/utils/isWebglSupported'>;
}
declare module 'react-three-renderer/lib/utils/PropTypeError.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/utils/PropTypeError'>;
}
declare module 'react-three-renderer/lib/utils/propTypeInstanceOf.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/utils/propTypeInstanceOf'>;
}
declare module 'react-three-renderer/lib/utils/removeDevTool.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/utils/removeDevTool'>;
}
declare module 'react-three-renderer/lib/Viewport.js' {
  declare module.exports: $Exports<'react-three-renderer/lib/Viewport'>;
}
declare module 'react-three-renderer/src/index.js' {
  declare module.exports: $Exports<'react-three-renderer/src/index'>;
}
declare module 'react-three-renderer/src/lib/descriptors/decorators/resource.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/decorators/resource'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/BoxGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/BoxGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/BufferGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/BufferGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/BufferGeometryDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/BufferGeometryDescriptorBase'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/CircleBufferGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/CircleBufferGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/CircleGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/CircleGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/CylinderGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/CylinderGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/DodecahedronGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/DodecahedronGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/EdgesGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/EdgesGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/ExtrudeGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/ExtrudeGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/GeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/GeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/GeometryDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/GeometryDescriptorBase'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/GeometryWithShapesDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/GeometryWithShapesDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/IcosahedronGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/IcosahedronGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/LatheGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/LatheGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/OctahedronGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/OctahedronGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/ParametricGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/ParametricGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/PlaneBufferGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/PlaneBufferGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/PlaneGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/PlaneGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/PolyhedronGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/PolyhedronGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/PolyhedronGeometryDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/PolyhedronGeometryDescriptorBase'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/RingGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/RingGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/ShapeGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/ShapeGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/AbsArcDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/Shapes/AbsArcDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/AbsEllipseDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/Shapes/AbsEllipseDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/BezierCurveToDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/Shapes/BezierCurveToDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/HoleDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/Shapes/HoleDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/LineToDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/Shapes/LineToDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/MoveToDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/Shapes/MoveToDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/PathDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/Shapes/PathDescriptorBase'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/QuadraticCurveToDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/Shapes/QuadraticCurveToDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/ShapeActionDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/Shapes/ShapeActionDescriptorBase'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/ShapeDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/Shapes/ShapeDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/Shapes/SplineThruDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/Shapes/SplineThruDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/SphereGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/SphereGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/TetrahedronGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/TetrahedronGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/TextGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/TextGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/TorusGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/TorusGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/TorusKnotGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/TorusKnotGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Geometry/TubeGeometryDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Geometry/TubeGeometryDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Light/AmbientLightDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Light/AmbientLightDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Light/DirectionalLightDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Light/DirectionalLightDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Light/HemisphereLightDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Light/HemisphereLightDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Light/LightDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Light/LightDescriptorBase'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Light/PointLightDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Light/PointLightDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Light/SpotLightDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Light/SpotLightDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/LineBasicMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/LineBasicMaterialDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/LineDashedMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/LineDashedMaterialDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/MaterialDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/MaterialDescriptorBase'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/MeshBasicMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/MeshBasicMaterialDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/MeshDepthMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/MeshDepthMaterialDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/MeshLambertMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/MeshLambertMaterialDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/MeshNormalMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/MeshNormalMaterialDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/MeshPhongMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/MeshPhongMaterialDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/MeshStandardMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/MeshStandardMaterialDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/PointsMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/PointsMaterialDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/RawShaderMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/RawShaderMaterialDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/ShaderMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/ShaderMaterialDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/SpriteMaterialDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/SpriteMaterialDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/TextureDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/TextureDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/UniformDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/UniformDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Material/UniformsDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Material/UniformsDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/ModuleDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/ModuleDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/Camera/CameraDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/Camera/CameraDescriptorBase'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/Camera/CubeCameraDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/Camera/CubeCameraDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/Camera/OrthographicCameraDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/Camera/OrthographicCameraDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/Camera/PerspectiveCameraDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/Camera/PerspectiveCameraDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/GroupDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/GroupDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/Helper/ArrowHelperDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/Helper/ArrowHelperDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/Helper/AxisHelperDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/Helper/AxisHelperDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/Helper/CameraHelperDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/Helper/CameraHelperDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/Helper/GridHelperDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/Helper/GridHelperDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/LineDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/LineDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/LineSegmentsDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/LineSegmentsDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/MeshDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/MeshDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/Object3DDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/Object3DDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/PointsDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/PointsDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/SceneDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/SceneDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Object/SpriteDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Object/SpriteDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/React3Descriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/React3Descriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Resource/GeometryResourceDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Resource/GeometryResourceDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Resource/MaterialResourceDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Resource/MaterialResourceDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Resource/ResourceDescriptorBase.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Resource/ResourceDescriptorBase'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Resource/ResourcesDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Resource/ResourcesDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Resource/ShapeGeometryResourceDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Resource/ShapeGeometryResourceDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Resource/ShapeResourceDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Resource/ShapeResourceDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/Resource/TextureResourceDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/Resource/TextureResourceDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/THREEElementDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/THREEElementDescriptor'>;
}
declare module 'react-three-renderer/src/lib/descriptors/ViewportDescriptor.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/descriptors/ViewportDescriptor'>;
}
declare module 'react-three-renderer/src/lib/ElementDescriptorContainer.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/ElementDescriptorContainer'>;
}
declare module 'react-three-renderer/src/lib/InternalComponent.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/InternalComponent'>;
}
declare module 'react-three-renderer/src/lib/Module.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Module'>;
}
declare module 'react-three-renderer/src/lib/React3.jsx' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/React3'>;
}
declare module 'react-three-renderer/src/lib/React3ComponentFlags.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/React3ComponentFlags'>;
}
declare module 'react-three-renderer/src/lib/React3ComponentTree.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/React3ComponentTree'>;
}
declare module 'react-three-renderer/src/lib/React3CompositeComponentWrapper.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/React3CompositeComponentWrapper'>;
}
declare module 'react-three-renderer/src/lib/React3ContainerInfo.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/React3ContainerInfo'>;
}
declare module 'react-three-renderer/src/lib/React3Instance.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/React3Instance'>;
}
declare module 'react-three-renderer/src/lib/React3Renderer.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/React3Renderer'>;
}
declare module 'react-three-renderer/src/lib/Resources/ResourceContainer.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Resources/ResourceContainer'>;
}
declare module 'react-three-renderer/src/lib/Resources/ResourceReference.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Resources/ResourceReference'>;
}
declare module 'react-three-renderer/src/lib/Resources/ShapeResourceReference.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Resources/ShapeResourceReference'>;
}
declare module 'react-three-renderer/src/lib/Shapes/AbsArcAction.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Shapes/AbsArcAction'>;
}
declare module 'react-three-renderer/src/lib/Shapes/AbsEllipseAction.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Shapes/AbsEllipseAction'>;
}
declare module 'react-three-renderer/src/lib/Shapes/BezierCurveToAction.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Shapes/BezierCurveToAction'>;
}
declare module 'react-three-renderer/src/lib/Shapes/HoleAction.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Shapes/HoleAction'>;
}
declare module 'react-three-renderer/src/lib/Shapes/LineToAction.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Shapes/LineToAction'>;
}
declare module 'react-three-renderer/src/lib/Shapes/MoveToAction.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Shapes/MoveToAction'>;
}
declare module 'react-three-renderer/src/lib/Shapes/QuadraticCurveToAction.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Shapes/QuadraticCurveToAction'>;
}
declare module 'react-three-renderer/src/lib/Shapes/ShapeAction.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Shapes/ShapeAction'>;
}
declare module 'react-three-renderer/src/lib/Shapes/SplineThruAction.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Shapes/SplineThruAction'>;
}
declare module 'react-three-renderer/src/lib/Uniform.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Uniform'>;
}
declare module 'react-three-renderer/src/lib/UniformContainer.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/UniformContainer'>;
}
declare module 'react-three-renderer/src/lib/utils/CameraUtils.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/utils/CameraUtils'>;
}
declare module 'react-three-renderer/src/lib/utils/EventDispatcher.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/utils/EventDispatcher'>;
}
declare module 'react-three-renderer/src/lib/utils/idPropertyName.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/utils/idPropertyName'>;
}
declare module 'react-three-renderer/src/lib/utils/isWebglSupported.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/utils/isWebglSupported'>;
}
declare module 'react-three-renderer/src/lib/utils/PropTypeError.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/utils/PropTypeError'>;
}
declare module 'react-three-renderer/src/lib/utils/propTypeInstanceOf.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/utils/propTypeInstanceOf'>;
}
declare module 'react-three-renderer/src/lib/utils/removeDevTool.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/utils/removeDevTool'>;
}
declare module 'react-three-renderer/src/lib/Viewport.js' {
  declare module.exports: $Exports<'react-three-renderer/src/lib/Viewport'>;
}
