// flow-typed signature: 8386c9d618caa120a656e3223de0cd6f
// flow-typed version: <<STUB>>/three.meshline_v^1.0.3/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'three.meshline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'three.meshline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'three.meshline/src/THREE.MeshLine' {
  declare module.exports: any;
}

// Filename aliases
declare module 'three.meshline/src/THREE.MeshLine.js' {
  declare module.exports: $Exports<'three.meshline/src/THREE.MeshLine'>;
}
