// flow-typed signature: 3a195f2748455870a09d496585f32bb3
// flow-typed version: <<STUB>>/three_v^0.86.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'three'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'three' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'three/build/three' {
  declare module.exports: any;
}

declare module 'three/build/three.min' {
  declare module.exports: any;
}

declare module 'three/build/three.module' {
  declare module.exports: any;
}

declare module 'three/src/animation/AnimationAction' {
  declare module.exports: any;
}

declare module 'three/src/animation/AnimationClip' {
  declare module.exports: any;
}

declare module 'three/src/animation/AnimationMixer' {
  declare module.exports: any;
}

declare module 'three/src/animation/AnimationObjectGroup' {
  declare module.exports: any;
}

declare module 'three/src/animation/AnimationUtils' {
  declare module.exports: any;
}

declare module 'three/src/animation/KeyframeTrack' {
  declare module.exports: any;
}

declare module 'three/src/animation/KeyframeTrackConstructor' {
  declare module.exports: any;
}

declare module 'three/src/animation/KeyframeTrackPrototype' {
  declare module.exports: any;
}

declare module 'three/src/animation/PropertyBinding' {
  declare module.exports: any;
}

declare module 'three/src/animation/PropertyMixer' {
  declare module.exports: any;
}

declare module 'three/src/animation/tracks/BooleanKeyframeTrack' {
  declare module.exports: any;
}

declare module 'three/src/animation/tracks/ColorKeyframeTrack' {
  declare module.exports: any;
}

declare module 'three/src/animation/tracks/NumberKeyframeTrack' {
  declare module.exports: any;
}

declare module 'three/src/animation/tracks/QuaternionKeyframeTrack' {
  declare module.exports: any;
}

declare module 'three/src/animation/tracks/StringKeyframeTrack' {
  declare module.exports: any;
}

declare module 'three/src/animation/tracks/VectorKeyframeTrack' {
  declare module.exports: any;
}

declare module 'three/src/audio/Audio' {
  declare module.exports: any;
}

declare module 'three/src/audio/AudioAnalyser' {
  declare module.exports: any;
}

declare module 'three/src/audio/AudioContext' {
  declare module.exports: any;
}

declare module 'three/src/audio/AudioListener' {
  declare module.exports: any;
}

declare module 'three/src/audio/PositionalAudio' {
  declare module.exports: any;
}

declare module 'three/src/cameras/ArrayCamera' {
  declare module.exports: any;
}

declare module 'three/src/cameras/Camera' {
  declare module.exports: any;
}

declare module 'three/src/cameras/CubeCamera' {
  declare module.exports: any;
}

declare module 'three/src/cameras/OrthographicCamera' {
  declare module.exports: any;
}

declare module 'three/src/cameras/PerspectiveCamera' {
  declare module.exports: any;
}

declare module 'three/src/cameras/StereoCamera' {
  declare module.exports: any;
}

declare module 'three/src/constants' {
  declare module.exports: any;
}

declare module 'three/src/core/BufferAttribute' {
  declare module.exports: any;
}

declare module 'three/src/core/BufferGeometry' {
  declare module.exports: any;
}

declare module 'three/src/core/Clock' {
  declare module.exports: any;
}

declare module 'three/src/core/DirectGeometry' {
  declare module.exports: any;
}

declare module 'three/src/core/EventDispatcher' {
  declare module.exports: any;
}

declare module 'three/src/core/Face3' {
  declare module.exports: any;
}

declare module 'three/src/core/Geometry' {
  declare module.exports: any;
}

declare module 'three/src/core/InstancedBufferAttribute' {
  declare module.exports: any;
}

declare module 'three/src/core/InstancedBufferGeometry' {
  declare module.exports: any;
}

declare module 'three/src/core/InstancedInterleavedBuffer' {
  declare module.exports: any;
}

declare module 'three/src/core/InterleavedBuffer' {
  declare module.exports: any;
}

declare module 'three/src/core/InterleavedBufferAttribute' {
  declare module.exports: any;
}

declare module 'three/src/core/Layers' {
  declare module.exports: any;
}

declare module 'three/src/core/Object3D' {
  declare module.exports: any;
}

declare module 'three/src/core/Raycaster' {
  declare module.exports: any;
}

declare module 'three/src/core/Uniform' {
  declare module.exports: any;
}

declare module 'three/src/extras/core/Curve' {
  declare module.exports: any;
}

declare module 'three/src/extras/core/CurvePath' {
  declare module.exports: any;
}

declare module 'three/src/extras/core/Font' {
  declare module.exports: any;
}

declare module 'three/src/extras/core/Interpolations' {
  declare module.exports: any;
}

declare module 'three/src/extras/core/Path' {
  declare module.exports: any;
}

declare module 'three/src/extras/core/PathPrototype' {
  declare module.exports: any;
}

declare module 'three/src/extras/core/Shape' {
  declare module.exports: any;
}

declare module 'three/src/extras/core/ShapePath' {
  declare module.exports: any;
}

declare module 'three/src/extras/curves/ArcCurve' {
  declare module.exports: any;
}

declare module 'three/src/extras/curves/CatmullRomCurve3' {
  declare module.exports: any;
}

declare module 'three/src/extras/curves/CubicBezierCurve' {
  declare module.exports: any;
}

declare module 'three/src/extras/curves/CubicBezierCurve3' {
  declare module.exports: any;
}

declare module 'three/src/extras/curves/EllipseCurve' {
  declare module.exports: any;
}

declare module 'three/src/extras/curves/LineCurve' {
  declare module.exports: any;
}

declare module 'three/src/extras/curves/LineCurve3' {
  declare module.exports: any;
}

declare module 'three/src/extras/curves/QuadraticBezierCurve' {
  declare module.exports: any;
}

declare module 'three/src/extras/curves/QuadraticBezierCurve3' {
  declare module.exports: any;
}

declare module 'three/src/extras/curves/SplineCurve' {
  declare module.exports: any;
}

declare module 'three/src/extras/objects/ImmediateRenderObject' {
  declare module.exports: any;
}

declare module 'three/src/extras/objects/MorphBlendMesh' {
  declare module.exports: any;
}

declare module 'three/src/extras/SceneUtils' {
  declare module.exports: any;
}

declare module 'three/src/extras/ShapeUtils' {
  declare module.exports: any;
}

declare module 'three/src/geometries/BoxGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/CircleGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/ConeGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/CylinderGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/DodecahedronGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/EdgesGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/ExtrudeGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/Geometries' {
  declare module.exports: any;
}

declare module 'three/src/geometries/IcosahedronGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/LatheGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/OctahedronGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/ParametricGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/PlaneGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/PolyhedronGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/RingGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/ShapeGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/SphereGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/TetrahedronGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/TextGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/TorusGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/TorusKnotGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/TubeGeometry' {
  declare module.exports: any;
}

declare module 'three/src/geometries/WireframeGeometry' {
  declare module.exports: any;
}

declare module 'three/src/helpers/ArrowHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/AxisHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/BoxHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/CameraHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/DirectionalLightHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/FaceNormalsHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/GridHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/HemisphereLightHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/PointLightHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/PolarGridHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/RectAreaLightHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/SkeletonHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/SpotLightHelper' {
  declare module.exports: any;
}

declare module 'three/src/helpers/VertexNormalsHelper' {
  declare module.exports: any;
}

declare module 'three/src/lights/AmbientLight' {
  declare module.exports: any;
}

declare module 'three/src/lights/DirectionalLight' {
  declare module.exports: any;
}

declare module 'three/src/lights/DirectionalLightShadow' {
  declare module.exports: any;
}

declare module 'three/src/lights/HemisphereLight' {
  declare module.exports: any;
}

declare module 'three/src/lights/Light' {
  declare module.exports: any;
}

declare module 'three/src/lights/LightShadow' {
  declare module.exports: any;
}

declare module 'three/src/lights/PointLight' {
  declare module.exports: any;
}

declare module 'three/src/lights/RectAreaLight' {
  declare module.exports: any;
}

declare module 'three/src/lights/SpotLight' {
  declare module.exports: any;
}

declare module 'three/src/lights/SpotLightShadow' {
  declare module.exports: any;
}

declare module 'three/src/loaders/AnimationLoader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/AudioLoader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/BufferGeometryLoader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/Cache' {
  declare module.exports: any;
}

declare module 'three/src/loaders/CompressedTextureLoader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/CubeTextureLoader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/DataTextureLoader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/FileLoader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/FontLoader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/ImageLoader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/JSONLoader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/Loader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/LoadingManager' {
  declare module.exports: any;
}

declare module 'three/src/loaders/MaterialLoader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/ObjectLoader' {
  declare module.exports: any;
}

declare module 'three/src/loaders/TextureLoader' {
  declare module.exports: any;
}

declare module 'three/src/materials/LineBasicMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/LineDashedMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/Material' {
  declare module.exports: any;
}

declare module 'three/src/materials/Materials' {
  declare module.exports: any;
}

declare module 'three/src/materials/MeshBasicMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/MeshDepthMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/MeshLambertMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/MeshNormalMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/MeshPhongMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/MeshPhysicalMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/MeshStandardMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/MeshToonMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/PointsMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/RawShaderMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/ShaderMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/ShadowMaterial' {
  declare module.exports: any;
}

declare module 'three/src/materials/SpriteMaterial' {
  declare module.exports: any;
}

declare module 'three/src/math/Box2' {
  declare module.exports: any;
}

declare module 'three/src/math/Box3' {
  declare module.exports: any;
}

declare module 'three/src/math/Color' {
  declare module.exports: any;
}

declare module 'three/src/math/Cylindrical' {
  declare module.exports: any;
}

declare module 'three/src/math/Euler' {
  declare module.exports: any;
}

declare module 'three/src/math/Frustum' {
  declare module.exports: any;
}

declare module 'three/src/math/Interpolant' {
  declare module.exports: any;
}

declare module 'three/src/math/interpolants/CubicInterpolant' {
  declare module.exports: any;
}

declare module 'three/src/math/interpolants/DiscreteInterpolant' {
  declare module.exports: any;
}

declare module 'three/src/math/interpolants/LinearInterpolant' {
  declare module.exports: any;
}

declare module 'three/src/math/interpolants/QuaternionLinearInterpolant' {
  declare module.exports: any;
}

declare module 'three/src/math/Line3' {
  declare module.exports: any;
}

declare module 'three/src/math/Math' {
  declare module.exports: any;
}

declare module 'three/src/math/Matrix3' {
  declare module.exports: any;
}

declare module 'three/src/math/Matrix4' {
  declare module.exports: any;
}

declare module 'three/src/math/Plane' {
  declare module.exports: any;
}

declare module 'three/src/math/Quaternion' {
  declare module.exports: any;
}

declare module 'three/src/math/Ray' {
  declare module.exports: any;
}

declare module 'three/src/math/Sphere' {
  declare module.exports: any;
}

declare module 'three/src/math/Spherical' {
  declare module.exports: any;
}

declare module 'three/src/math/Triangle' {
  declare module.exports: any;
}

declare module 'three/src/math/Vector2' {
  declare module.exports: any;
}

declare module 'three/src/math/Vector3' {
  declare module.exports: any;
}

declare module 'three/src/math/Vector4' {
  declare module.exports: any;
}

declare module 'three/src/objects/Bone' {
  declare module.exports: any;
}

declare module 'three/src/objects/Group' {
  declare module.exports: any;
}

declare module 'three/src/objects/LensFlare' {
  declare module.exports: any;
}

declare module 'three/src/objects/Line' {
  declare module.exports: any;
}

declare module 'three/src/objects/LineLoop' {
  declare module.exports: any;
}

declare module 'three/src/objects/LineSegments' {
  declare module.exports: any;
}

declare module 'three/src/objects/LOD' {
  declare module.exports: any;
}

declare module 'three/src/objects/Mesh' {
  declare module.exports: any;
}

declare module 'three/src/objects/Points' {
  declare module.exports: any;
}

declare module 'three/src/objects/Skeleton' {
  declare module.exports: any;
}

declare module 'three/src/objects/SkinnedMesh' {
  declare module.exports: any;
}

declare module 'three/src/objects/Sprite' {
  declare module.exports: any;
}

declare module 'three/src/polyfills' {
  declare module.exports: any;
}

declare module 'three/src/renderers/shaders/ShaderChunk' {
  declare module.exports: any;
}

declare module 'three/src/renderers/shaders/ShaderLib' {
  declare module.exports: any;
}

declare module 'three/src/renderers/shaders/UniformsLib' {
  declare module.exports: any;
}

declare module 'three/src/renderers/shaders/UniformsUtils' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/plugins/LensFlarePlugin' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/plugins/SpritePlugin' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLAttributes' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLBackground' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLBufferRenderer' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLCapabilities' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLClipping' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLExtensions' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLGeometries' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLIndexedBufferRenderer' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLLights' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLObjects' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLProgram' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLPrograms' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLProperties' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLRenderLists' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLShader' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLShadowMap' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLState' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLTextures' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webgl/WebGLUniforms' {
  declare module.exports: any;
}

declare module 'three/src/renderers/WebGL2Renderer' {
  declare module.exports: any;
}

declare module 'three/src/renderers/WebGLRenderer' {
  declare module.exports: any;
}

declare module 'three/src/renderers/WebGLRenderTarget' {
  declare module.exports: any;
}

declare module 'three/src/renderers/WebGLRenderTargetCube' {
  declare module.exports: any;
}

declare module 'three/src/renderers/webvr/WebVRManager' {
  declare module.exports: any;
}

declare module 'three/src/scenes/Fog' {
  declare module.exports: any;
}

declare module 'three/src/scenes/FogExp2' {
  declare module.exports: any;
}

declare module 'three/src/scenes/Scene' {
  declare module.exports: any;
}

declare module 'three/src/textures/CanvasTexture' {
  declare module.exports: any;
}

declare module 'three/src/textures/CompressedTexture' {
  declare module.exports: any;
}

declare module 'three/src/textures/CubeTexture' {
  declare module.exports: any;
}

declare module 'three/src/textures/DataTexture' {
  declare module.exports: any;
}

declare module 'three/src/textures/DepthTexture' {
  declare module.exports: any;
}

declare module 'three/src/textures/Texture' {
  declare module.exports: any;
}

declare module 'three/src/textures/VideoTexture' {
  declare module.exports: any;
}

declare module 'three/src/Three' {
  declare module.exports: any;
}

declare module 'three/src/Three.Legacy' {
  declare module.exports: any;
}

declare module 'three/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'three/build/three.js' {
  declare module.exports: $Exports<'three/build/three'>;
}
declare module 'three/build/three.min.js' {
  declare module.exports: $Exports<'three/build/three.min'>;
}
declare module 'three/build/three.module.js' {
  declare module.exports: $Exports<'three/build/three.module'>;
}
declare module 'three/src/animation/AnimationAction.js' {
  declare module.exports: $Exports<'three/src/animation/AnimationAction'>;
}
declare module 'three/src/animation/AnimationClip.js' {
  declare module.exports: $Exports<'three/src/animation/AnimationClip'>;
}
declare module 'three/src/animation/AnimationMixer.js' {
  declare module.exports: $Exports<'three/src/animation/AnimationMixer'>;
}
declare module 'three/src/animation/AnimationObjectGroup.js' {
  declare module.exports: $Exports<'three/src/animation/AnimationObjectGroup'>;
}
declare module 'three/src/animation/AnimationUtils.js' {
  declare module.exports: $Exports<'three/src/animation/AnimationUtils'>;
}
declare module 'three/src/animation/KeyframeTrack.js' {
  declare module.exports: $Exports<'three/src/animation/KeyframeTrack'>;
}
declare module 'three/src/animation/KeyframeTrackConstructor.js' {
  declare module.exports: $Exports<'three/src/animation/KeyframeTrackConstructor'>;
}
declare module 'three/src/animation/KeyframeTrackPrototype.js' {
  declare module.exports: $Exports<'three/src/animation/KeyframeTrackPrototype'>;
}
declare module 'three/src/animation/PropertyBinding.js' {
  declare module.exports: $Exports<'three/src/animation/PropertyBinding'>;
}
declare module 'three/src/animation/PropertyMixer.js' {
  declare module.exports: $Exports<'three/src/animation/PropertyMixer'>;
}
declare module 'three/src/animation/tracks/BooleanKeyframeTrack.js' {
  declare module.exports: $Exports<'three/src/animation/tracks/BooleanKeyframeTrack'>;
}
declare module 'three/src/animation/tracks/ColorKeyframeTrack.js' {
  declare module.exports: $Exports<'three/src/animation/tracks/ColorKeyframeTrack'>;
}
declare module 'three/src/animation/tracks/NumberKeyframeTrack.js' {
  declare module.exports: $Exports<'three/src/animation/tracks/NumberKeyframeTrack'>;
}
declare module 'three/src/animation/tracks/QuaternionKeyframeTrack.js' {
  declare module.exports: $Exports<'three/src/animation/tracks/QuaternionKeyframeTrack'>;
}
declare module 'three/src/animation/tracks/StringKeyframeTrack.js' {
  declare module.exports: $Exports<'three/src/animation/tracks/StringKeyframeTrack'>;
}
declare module 'three/src/animation/tracks/VectorKeyframeTrack.js' {
  declare module.exports: $Exports<'three/src/animation/tracks/VectorKeyframeTrack'>;
}
declare module 'three/src/audio/Audio.js' {
  declare module.exports: $Exports<'three/src/audio/Audio'>;
}
declare module 'three/src/audio/AudioAnalyser.js' {
  declare module.exports: $Exports<'three/src/audio/AudioAnalyser'>;
}
declare module 'three/src/audio/AudioContext.js' {
  declare module.exports: $Exports<'three/src/audio/AudioContext'>;
}
declare module 'three/src/audio/AudioListener.js' {
  declare module.exports: $Exports<'three/src/audio/AudioListener'>;
}
declare module 'three/src/audio/PositionalAudio.js' {
  declare module.exports: $Exports<'three/src/audio/PositionalAudio'>;
}
declare module 'three/src/cameras/ArrayCamera.js' {
  declare module.exports: $Exports<'three/src/cameras/ArrayCamera'>;
}
declare module 'three/src/cameras/Camera.js' {
  declare module.exports: $Exports<'three/src/cameras/Camera'>;
}
declare module 'three/src/cameras/CubeCamera.js' {
  declare module.exports: $Exports<'three/src/cameras/CubeCamera'>;
}
declare module 'three/src/cameras/OrthographicCamera.js' {
  declare module.exports: $Exports<'three/src/cameras/OrthographicCamera'>;
}
declare module 'three/src/cameras/PerspectiveCamera.js' {
  declare module.exports: $Exports<'three/src/cameras/PerspectiveCamera'>;
}
declare module 'three/src/cameras/StereoCamera.js' {
  declare module.exports: $Exports<'three/src/cameras/StereoCamera'>;
}
declare module 'three/src/constants.js' {
  declare module.exports: $Exports<'three/src/constants'>;
}
declare module 'three/src/core/BufferAttribute.js' {
  declare module.exports: $Exports<'three/src/core/BufferAttribute'>;
}
declare module 'three/src/core/BufferGeometry.js' {
  declare module.exports: $Exports<'three/src/core/BufferGeometry'>;
}
declare module 'three/src/core/Clock.js' {
  declare module.exports: $Exports<'three/src/core/Clock'>;
}
declare module 'three/src/core/DirectGeometry.js' {
  declare module.exports: $Exports<'three/src/core/DirectGeometry'>;
}
declare module 'three/src/core/EventDispatcher.js' {
  declare module.exports: $Exports<'three/src/core/EventDispatcher'>;
}
declare module 'three/src/core/Face3.js' {
  declare module.exports: $Exports<'three/src/core/Face3'>;
}
declare module 'three/src/core/Geometry.js' {
  declare module.exports: $Exports<'three/src/core/Geometry'>;
}
declare module 'three/src/core/InstancedBufferAttribute.js' {
  declare module.exports: $Exports<'three/src/core/InstancedBufferAttribute'>;
}
declare module 'three/src/core/InstancedBufferGeometry.js' {
  declare module.exports: $Exports<'three/src/core/InstancedBufferGeometry'>;
}
declare module 'three/src/core/InstancedInterleavedBuffer.js' {
  declare module.exports: $Exports<'three/src/core/InstancedInterleavedBuffer'>;
}
declare module 'three/src/core/InterleavedBuffer.js' {
  declare module.exports: $Exports<'three/src/core/InterleavedBuffer'>;
}
declare module 'three/src/core/InterleavedBufferAttribute.js' {
  declare module.exports: $Exports<'three/src/core/InterleavedBufferAttribute'>;
}
declare module 'three/src/core/Layers.js' {
  declare module.exports: $Exports<'three/src/core/Layers'>;
}
declare module 'three/src/core/Object3D.js' {
  declare module.exports: $Exports<'three/src/core/Object3D'>;
}
declare module 'three/src/core/Raycaster.js' {
  declare module.exports: $Exports<'three/src/core/Raycaster'>;
}
declare module 'three/src/core/Uniform.js' {
  declare module.exports: $Exports<'three/src/core/Uniform'>;
}
declare module 'three/src/extras/core/Curve.js' {
  declare module.exports: $Exports<'three/src/extras/core/Curve'>;
}
declare module 'three/src/extras/core/CurvePath.js' {
  declare module.exports: $Exports<'three/src/extras/core/CurvePath'>;
}
declare module 'three/src/extras/core/Font.js' {
  declare module.exports: $Exports<'three/src/extras/core/Font'>;
}
declare module 'three/src/extras/core/Interpolations.js' {
  declare module.exports: $Exports<'three/src/extras/core/Interpolations'>;
}
declare module 'three/src/extras/core/Path.js' {
  declare module.exports: $Exports<'three/src/extras/core/Path'>;
}
declare module 'three/src/extras/core/PathPrototype.js' {
  declare module.exports: $Exports<'three/src/extras/core/PathPrototype'>;
}
declare module 'three/src/extras/core/Shape.js' {
  declare module.exports: $Exports<'three/src/extras/core/Shape'>;
}
declare module 'three/src/extras/core/ShapePath.js' {
  declare module.exports: $Exports<'three/src/extras/core/ShapePath'>;
}
declare module 'three/src/extras/curves/ArcCurve.js' {
  declare module.exports: $Exports<'three/src/extras/curves/ArcCurve'>;
}
declare module 'three/src/extras/curves/CatmullRomCurve3.js' {
  declare module.exports: $Exports<'three/src/extras/curves/CatmullRomCurve3'>;
}
declare module 'three/src/extras/curves/CubicBezierCurve.js' {
  declare module.exports: $Exports<'three/src/extras/curves/CubicBezierCurve'>;
}
declare module 'three/src/extras/curves/CubicBezierCurve3.js' {
  declare module.exports: $Exports<'three/src/extras/curves/CubicBezierCurve3'>;
}
declare module 'three/src/extras/curves/EllipseCurve.js' {
  declare module.exports: $Exports<'three/src/extras/curves/EllipseCurve'>;
}
declare module 'three/src/extras/curves/LineCurve.js' {
  declare module.exports: $Exports<'three/src/extras/curves/LineCurve'>;
}
declare module 'three/src/extras/curves/LineCurve3.js' {
  declare module.exports: $Exports<'three/src/extras/curves/LineCurve3'>;
}
declare module 'three/src/extras/curves/QuadraticBezierCurve.js' {
  declare module.exports: $Exports<'three/src/extras/curves/QuadraticBezierCurve'>;
}
declare module 'three/src/extras/curves/QuadraticBezierCurve3.js' {
  declare module.exports: $Exports<'three/src/extras/curves/QuadraticBezierCurve3'>;
}
declare module 'three/src/extras/curves/SplineCurve.js' {
  declare module.exports: $Exports<'three/src/extras/curves/SplineCurve'>;
}
declare module 'three/src/extras/objects/ImmediateRenderObject.js' {
  declare module.exports: $Exports<'three/src/extras/objects/ImmediateRenderObject'>;
}
declare module 'three/src/extras/objects/MorphBlendMesh.js' {
  declare module.exports: $Exports<'three/src/extras/objects/MorphBlendMesh'>;
}
declare module 'three/src/extras/SceneUtils.js' {
  declare module.exports: $Exports<'three/src/extras/SceneUtils'>;
}
declare module 'three/src/extras/ShapeUtils.js' {
  declare module.exports: $Exports<'three/src/extras/ShapeUtils'>;
}
declare module 'three/src/geometries/BoxGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/BoxGeometry'>;
}
declare module 'three/src/geometries/CircleGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/CircleGeometry'>;
}
declare module 'three/src/geometries/ConeGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/ConeGeometry'>;
}
declare module 'three/src/geometries/CylinderGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/CylinderGeometry'>;
}
declare module 'three/src/geometries/DodecahedronGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/DodecahedronGeometry'>;
}
declare module 'three/src/geometries/EdgesGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/EdgesGeometry'>;
}
declare module 'three/src/geometries/ExtrudeGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/ExtrudeGeometry'>;
}
declare module 'three/src/geometries/Geometries.js' {
  declare module.exports: $Exports<'three/src/geometries/Geometries'>;
}
declare module 'three/src/geometries/IcosahedronGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/IcosahedronGeometry'>;
}
declare module 'three/src/geometries/LatheGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/LatheGeometry'>;
}
declare module 'three/src/geometries/OctahedronGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/OctahedronGeometry'>;
}
declare module 'three/src/geometries/ParametricGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/ParametricGeometry'>;
}
declare module 'three/src/geometries/PlaneGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/PlaneGeometry'>;
}
declare module 'three/src/geometries/PolyhedronGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/PolyhedronGeometry'>;
}
declare module 'three/src/geometries/RingGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/RingGeometry'>;
}
declare module 'three/src/geometries/ShapeGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/ShapeGeometry'>;
}
declare module 'three/src/geometries/SphereGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/SphereGeometry'>;
}
declare module 'three/src/geometries/TetrahedronGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/TetrahedronGeometry'>;
}
declare module 'three/src/geometries/TextGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/TextGeometry'>;
}
declare module 'three/src/geometries/TorusGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/TorusGeometry'>;
}
declare module 'three/src/geometries/TorusKnotGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/TorusKnotGeometry'>;
}
declare module 'three/src/geometries/TubeGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/TubeGeometry'>;
}
declare module 'three/src/geometries/WireframeGeometry.js' {
  declare module.exports: $Exports<'three/src/geometries/WireframeGeometry'>;
}
declare module 'three/src/helpers/ArrowHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/ArrowHelper'>;
}
declare module 'three/src/helpers/AxisHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/AxisHelper'>;
}
declare module 'three/src/helpers/BoxHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/BoxHelper'>;
}
declare module 'three/src/helpers/CameraHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/CameraHelper'>;
}
declare module 'three/src/helpers/DirectionalLightHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/DirectionalLightHelper'>;
}
declare module 'three/src/helpers/FaceNormalsHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/FaceNormalsHelper'>;
}
declare module 'three/src/helpers/GridHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/GridHelper'>;
}
declare module 'three/src/helpers/HemisphereLightHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/HemisphereLightHelper'>;
}
declare module 'three/src/helpers/PointLightHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/PointLightHelper'>;
}
declare module 'three/src/helpers/PolarGridHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/PolarGridHelper'>;
}
declare module 'three/src/helpers/RectAreaLightHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/RectAreaLightHelper'>;
}
declare module 'three/src/helpers/SkeletonHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/SkeletonHelper'>;
}
declare module 'three/src/helpers/SpotLightHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/SpotLightHelper'>;
}
declare module 'three/src/helpers/VertexNormalsHelper.js' {
  declare module.exports: $Exports<'three/src/helpers/VertexNormalsHelper'>;
}
declare module 'three/src/lights/AmbientLight.js' {
  declare module.exports: $Exports<'three/src/lights/AmbientLight'>;
}
declare module 'three/src/lights/DirectionalLight.js' {
  declare module.exports: $Exports<'three/src/lights/DirectionalLight'>;
}
declare module 'three/src/lights/DirectionalLightShadow.js' {
  declare module.exports: $Exports<'three/src/lights/DirectionalLightShadow'>;
}
declare module 'three/src/lights/HemisphereLight.js' {
  declare module.exports: $Exports<'three/src/lights/HemisphereLight'>;
}
declare module 'three/src/lights/Light.js' {
  declare module.exports: $Exports<'three/src/lights/Light'>;
}
declare module 'three/src/lights/LightShadow.js' {
  declare module.exports: $Exports<'three/src/lights/LightShadow'>;
}
declare module 'three/src/lights/PointLight.js' {
  declare module.exports: $Exports<'three/src/lights/PointLight'>;
}
declare module 'three/src/lights/RectAreaLight.js' {
  declare module.exports: $Exports<'three/src/lights/RectAreaLight'>;
}
declare module 'three/src/lights/SpotLight.js' {
  declare module.exports: $Exports<'three/src/lights/SpotLight'>;
}
declare module 'three/src/lights/SpotLightShadow.js' {
  declare module.exports: $Exports<'three/src/lights/SpotLightShadow'>;
}
declare module 'three/src/loaders/AnimationLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/AnimationLoader'>;
}
declare module 'three/src/loaders/AudioLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/AudioLoader'>;
}
declare module 'three/src/loaders/BufferGeometryLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/BufferGeometryLoader'>;
}
declare module 'three/src/loaders/Cache.js' {
  declare module.exports: $Exports<'three/src/loaders/Cache'>;
}
declare module 'three/src/loaders/CompressedTextureLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/CompressedTextureLoader'>;
}
declare module 'three/src/loaders/CubeTextureLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/CubeTextureLoader'>;
}
declare module 'three/src/loaders/DataTextureLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/DataTextureLoader'>;
}
declare module 'three/src/loaders/FileLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/FileLoader'>;
}
declare module 'three/src/loaders/FontLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/FontLoader'>;
}
declare module 'three/src/loaders/ImageLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/ImageLoader'>;
}
declare module 'three/src/loaders/JSONLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/JSONLoader'>;
}
declare module 'three/src/loaders/Loader.js' {
  declare module.exports: $Exports<'three/src/loaders/Loader'>;
}
declare module 'three/src/loaders/LoadingManager.js' {
  declare module.exports: $Exports<'three/src/loaders/LoadingManager'>;
}
declare module 'three/src/loaders/MaterialLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/MaterialLoader'>;
}
declare module 'three/src/loaders/ObjectLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/ObjectLoader'>;
}
declare module 'three/src/loaders/TextureLoader.js' {
  declare module.exports: $Exports<'three/src/loaders/TextureLoader'>;
}
declare module 'three/src/materials/LineBasicMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/LineBasicMaterial'>;
}
declare module 'three/src/materials/LineDashedMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/LineDashedMaterial'>;
}
declare module 'three/src/materials/Material.js' {
  declare module.exports: $Exports<'three/src/materials/Material'>;
}
declare module 'three/src/materials/Materials.js' {
  declare module.exports: $Exports<'three/src/materials/Materials'>;
}
declare module 'three/src/materials/MeshBasicMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/MeshBasicMaterial'>;
}
declare module 'three/src/materials/MeshDepthMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/MeshDepthMaterial'>;
}
declare module 'three/src/materials/MeshLambertMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/MeshLambertMaterial'>;
}
declare module 'three/src/materials/MeshNormalMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/MeshNormalMaterial'>;
}
declare module 'three/src/materials/MeshPhongMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/MeshPhongMaterial'>;
}
declare module 'three/src/materials/MeshPhysicalMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/MeshPhysicalMaterial'>;
}
declare module 'three/src/materials/MeshStandardMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/MeshStandardMaterial'>;
}
declare module 'three/src/materials/MeshToonMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/MeshToonMaterial'>;
}
declare module 'three/src/materials/PointsMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/PointsMaterial'>;
}
declare module 'three/src/materials/RawShaderMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/RawShaderMaterial'>;
}
declare module 'three/src/materials/ShaderMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/ShaderMaterial'>;
}
declare module 'three/src/materials/ShadowMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/ShadowMaterial'>;
}
declare module 'three/src/materials/SpriteMaterial.js' {
  declare module.exports: $Exports<'three/src/materials/SpriteMaterial'>;
}
declare module 'three/src/math/Box2.js' {
  declare module.exports: $Exports<'three/src/math/Box2'>;
}
declare module 'three/src/math/Box3.js' {
  declare module.exports: $Exports<'three/src/math/Box3'>;
}
declare module 'three/src/math/Color.js' {
  declare module.exports: $Exports<'three/src/math/Color'>;
}
declare module 'three/src/math/Cylindrical.js' {
  declare module.exports: $Exports<'three/src/math/Cylindrical'>;
}
declare module 'three/src/math/Euler.js' {
  declare module.exports: $Exports<'three/src/math/Euler'>;
}
declare module 'three/src/math/Frustum.js' {
  declare module.exports: $Exports<'three/src/math/Frustum'>;
}
declare module 'three/src/math/Interpolant.js' {
  declare module.exports: $Exports<'three/src/math/Interpolant'>;
}
declare module 'three/src/math/interpolants/CubicInterpolant.js' {
  declare module.exports: $Exports<'three/src/math/interpolants/CubicInterpolant'>;
}
declare module 'three/src/math/interpolants/DiscreteInterpolant.js' {
  declare module.exports: $Exports<'three/src/math/interpolants/DiscreteInterpolant'>;
}
declare module 'three/src/math/interpolants/LinearInterpolant.js' {
  declare module.exports: $Exports<'three/src/math/interpolants/LinearInterpolant'>;
}
declare module 'three/src/math/interpolants/QuaternionLinearInterpolant.js' {
  declare module.exports: $Exports<'three/src/math/interpolants/QuaternionLinearInterpolant'>;
}
declare module 'three/src/math/Line3.js' {
  declare module.exports: $Exports<'three/src/math/Line3'>;
}
declare module 'three/src/math/Math.js' {
  declare module.exports: $Exports<'three/src/math/Math'>;
}
declare module 'three/src/math/Matrix3.js' {
  declare module.exports: $Exports<'three/src/math/Matrix3'>;
}
declare module 'three/src/math/Matrix4.js' {
  declare module.exports: $Exports<'three/src/math/Matrix4'>;
}
declare module 'three/src/math/Plane.js' {
  declare module.exports: $Exports<'three/src/math/Plane'>;
}
declare module 'three/src/math/Quaternion.js' {
  declare module.exports: $Exports<'three/src/math/Quaternion'>;
}
declare module 'three/src/math/Ray.js' {
  declare module.exports: $Exports<'three/src/math/Ray'>;
}
declare module 'three/src/math/Sphere.js' {
  declare module.exports: $Exports<'three/src/math/Sphere'>;
}
declare module 'three/src/math/Spherical.js' {
  declare module.exports: $Exports<'three/src/math/Spherical'>;
}
declare module 'three/src/math/Triangle.js' {
  declare module.exports: $Exports<'three/src/math/Triangle'>;
}
declare module 'three/src/math/Vector2.js' {
  declare module.exports: $Exports<'three/src/math/Vector2'>;
}
declare module 'three/src/math/Vector3.js' {
  declare module.exports: $Exports<'three/src/math/Vector3'>;
}
declare module 'three/src/math/Vector4.js' {
  declare module.exports: $Exports<'three/src/math/Vector4'>;
}
declare module 'three/src/objects/Bone.js' {
  declare module.exports: $Exports<'three/src/objects/Bone'>;
}
declare module 'three/src/objects/Group.js' {
  declare module.exports: $Exports<'three/src/objects/Group'>;
}
declare module 'three/src/objects/LensFlare.js' {
  declare module.exports: $Exports<'three/src/objects/LensFlare'>;
}
declare module 'three/src/objects/Line.js' {
  declare module.exports: $Exports<'three/src/objects/Line'>;
}
declare module 'three/src/objects/LineLoop.js' {
  declare module.exports: $Exports<'three/src/objects/LineLoop'>;
}
declare module 'three/src/objects/LineSegments.js' {
  declare module.exports: $Exports<'three/src/objects/LineSegments'>;
}
declare module 'three/src/objects/LOD.js' {
  declare module.exports: $Exports<'three/src/objects/LOD'>;
}
declare module 'three/src/objects/Mesh.js' {
  declare module.exports: $Exports<'three/src/objects/Mesh'>;
}
declare module 'three/src/objects/Points.js' {
  declare module.exports: $Exports<'three/src/objects/Points'>;
}
declare module 'three/src/objects/Skeleton.js' {
  declare module.exports: $Exports<'three/src/objects/Skeleton'>;
}
declare module 'three/src/objects/SkinnedMesh.js' {
  declare module.exports: $Exports<'three/src/objects/SkinnedMesh'>;
}
declare module 'three/src/objects/Sprite.js' {
  declare module.exports: $Exports<'three/src/objects/Sprite'>;
}
declare module 'three/src/polyfills.js' {
  declare module.exports: $Exports<'three/src/polyfills'>;
}
declare module 'three/src/renderers/shaders/ShaderChunk.js' {
  declare module.exports: $Exports<'three/src/renderers/shaders/ShaderChunk'>;
}
declare module 'three/src/renderers/shaders/ShaderLib.js' {
  declare module.exports: $Exports<'three/src/renderers/shaders/ShaderLib'>;
}
declare module 'three/src/renderers/shaders/UniformsLib.js' {
  declare module.exports: $Exports<'three/src/renderers/shaders/UniformsLib'>;
}
declare module 'three/src/renderers/shaders/UniformsUtils.js' {
  declare module.exports: $Exports<'three/src/renderers/shaders/UniformsUtils'>;
}
declare module 'three/src/renderers/webgl/plugins/LensFlarePlugin.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/plugins/LensFlarePlugin'>;
}
declare module 'three/src/renderers/webgl/plugins/SpritePlugin.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/plugins/SpritePlugin'>;
}
declare module 'three/src/renderers/webgl/WebGLAttributes.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLAttributes'>;
}
declare module 'three/src/renderers/webgl/WebGLBackground.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLBackground'>;
}
declare module 'three/src/renderers/webgl/WebGLBufferRenderer.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLBufferRenderer'>;
}
declare module 'three/src/renderers/webgl/WebGLCapabilities.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLCapabilities'>;
}
declare module 'three/src/renderers/webgl/WebGLClipping.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLClipping'>;
}
declare module 'three/src/renderers/webgl/WebGLExtensions.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLExtensions'>;
}
declare module 'three/src/renderers/webgl/WebGLGeometries.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLGeometries'>;
}
declare module 'three/src/renderers/webgl/WebGLIndexedBufferRenderer.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLIndexedBufferRenderer'>;
}
declare module 'three/src/renderers/webgl/WebGLLights.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLLights'>;
}
declare module 'three/src/renderers/webgl/WebGLObjects.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLObjects'>;
}
declare module 'three/src/renderers/webgl/WebGLProgram.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLProgram'>;
}
declare module 'three/src/renderers/webgl/WebGLPrograms.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLPrograms'>;
}
declare module 'three/src/renderers/webgl/WebGLProperties.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLProperties'>;
}
declare module 'three/src/renderers/webgl/WebGLRenderLists.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLRenderLists'>;
}
declare module 'three/src/renderers/webgl/WebGLShader.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLShader'>;
}
declare module 'three/src/renderers/webgl/WebGLShadowMap.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLShadowMap'>;
}
declare module 'three/src/renderers/webgl/WebGLState.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLState'>;
}
declare module 'three/src/renderers/webgl/WebGLTextures.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLTextures'>;
}
declare module 'three/src/renderers/webgl/WebGLUniforms.js' {
  declare module.exports: $Exports<'three/src/renderers/webgl/WebGLUniforms'>;
}
declare module 'three/src/renderers/WebGL2Renderer.js' {
  declare module.exports: $Exports<'three/src/renderers/WebGL2Renderer'>;
}
declare module 'three/src/renderers/WebGLRenderer.js' {
  declare module.exports: $Exports<'three/src/renderers/WebGLRenderer'>;
}
declare module 'three/src/renderers/WebGLRenderTarget.js' {
  declare module.exports: $Exports<'three/src/renderers/WebGLRenderTarget'>;
}
declare module 'three/src/renderers/WebGLRenderTargetCube.js' {
  declare module.exports: $Exports<'three/src/renderers/WebGLRenderTargetCube'>;
}
declare module 'three/src/renderers/webvr/WebVRManager.js' {
  declare module.exports: $Exports<'three/src/renderers/webvr/WebVRManager'>;
}
declare module 'three/src/scenes/Fog.js' {
  declare module.exports: $Exports<'three/src/scenes/Fog'>;
}
declare module 'three/src/scenes/FogExp2.js' {
  declare module.exports: $Exports<'three/src/scenes/FogExp2'>;
}
declare module 'three/src/scenes/Scene.js' {
  declare module.exports: $Exports<'three/src/scenes/Scene'>;
}
declare module 'three/src/textures/CanvasTexture.js' {
  declare module.exports: $Exports<'three/src/textures/CanvasTexture'>;
}
declare module 'three/src/textures/CompressedTexture.js' {
  declare module.exports: $Exports<'three/src/textures/CompressedTexture'>;
}
declare module 'three/src/textures/CubeTexture.js' {
  declare module.exports: $Exports<'three/src/textures/CubeTexture'>;
}
declare module 'three/src/textures/DataTexture.js' {
  declare module.exports: $Exports<'three/src/textures/DataTexture'>;
}
declare module 'three/src/textures/DepthTexture.js' {
  declare module.exports: $Exports<'three/src/textures/DepthTexture'>;
}
declare module 'three/src/textures/Texture.js' {
  declare module.exports: $Exports<'three/src/textures/Texture'>;
}
declare module 'three/src/textures/VideoTexture.js' {
  declare module.exports: $Exports<'three/src/textures/VideoTexture'>;
}
declare module 'three/src/Three.js' {
  declare module.exports: $Exports<'three/src/Three'>;
}
declare module 'three/src/Three.Legacy.js' {
  declare module.exports: $Exports<'three/src/Three.Legacy'>;
}
declare module 'three/src/utils.js' {
  declare module.exports: $Exports<'three/src/utils'>;
}
